### ISSUE TITLE
Cannot read code_128 barcodes in iOs

### ISSUE THREAD

**Issue by cfsqad** [Telerik-Verified-Plugins/BarcodeScanner#14]
Hello, 

As part of my project, I have to read a code_128 type barcode. 
It mostly works on android devices, although sometimes it gets only part of the barcode and understands it as a UPC_E type, but for iOs devices, it doesn't seem to work at all. I point the camera to the barcode for several minutes and nothing happens. 

Have anyone worked on code_128 barcodes before?

Regards,
Carina.

**Comment by EddyVerbruggen** [comment]
It could be this has to do with the amount of detail in the barcode s it's a [very high density format](https://en.wikipedia.org/wiki/Code_128). I've bumped the sensitivity of the iOS scanner from medium to high and have seen some good results with that.

I'll release a new version soon, but you can already grab the update from this repo's master branch.
