### ISSUE TITLE
Dead link in readme.md

### ISSUE THREAD

**Issue by spottuit** [Telerik-Verified-Plugins/BarcodeScanner#16]
The link "Cordova Plugin spec" (https://github.com/apache/cordova-plugman/blob/master/plugin_spec.md) is not working.

![image](https://cloud.githubusercontent.com/assets/9430751/11030824/c706dd34-86d0-11e5-9886-328b9c5a5c7c.png)

**Comment by spottuit** [comment]
I just found out there are two more dead links:
![image](https://cloud.githubusercontent.com/assets/9430751/11030876/12c53626-86d1-11e5-8dff-9b8d72511e4c.png)

**Comment by EddyVerbruggen** [comment]
Thanks - we could remove those bits as they are a bit outdated. But it would be even better to do it at the upstream repo since this is fork.

**Comment by spottuit** [comment]
The links in the main repository work so I guess you need to pull those changes. Just so you know that.

**Comment by EddyVerbruggen** [comment]
Good call, thx

**Comment by spottuit** [comment]
No problem, but I have a question. Do I need to specify some configuration in the config.xml for the plugin? The answer is probably yes right? If so you would probably want to add that configuration to the readme.md so people can get this plugin working after they build it with PhoneGap Build. My guess is I need to add this (I tried it and it worked):

```xml
<gap:plugin name="com.phonegap.plugins.barcodescanner" version="2.2.0" />
```

But that's confusing me. Is the main repository the code I get when I install the plugin or is it this repository? My main question is what's the point of having these two repositories? Maybe it's obvious, but please explain I am curious. My guess is that both repositories are different plugins.

**Comment by EddyVerbruggen** [comment]
This repo is a fork, mainly used for users of the [Telerik Platform](https://platform.telerik.com). You can however install it via the Cordova CLI. You can't use this one on PhoneGap Build since this fork is not on npm (yet anyway).

That line you posted will add the upstream repo to your project.
