### ISSUE TITLE
Forcing landscape on camera android

### ISSUE THREAD

**Issue by spottuit** [Telerik-Verified-Plugins/BarcodeScanner#17]
When I encountered this plugin I saw configuration that forces an orientation on Android. That's what I want to do with the camera. I want to force it to stay landscape. 
This is the webpage where I found it:
http://plugins.telerik.com/cordova/plugin/barcodescanner

Go to the heading "Forcing an orientation on Android" and you will see the configuration.

I already tried to get help on:
- Stackoverflow(http://stackoverflow.com/q/33571047/4815184)
- community.phonegap.com(http://gsfn.us/t/4sxfp)

I want to put the configuration in the config.xml like this:
```xml
 <gap:config-file target="AndroidManifest.xml" parent="/manifest/application" mode="merge">
    <activity
        android:name="com.google.zxing.client.android.CaptureActivity"
        android:screenOrientation="landscape"
        android:clearTaskOnLaunch="true"
        android:configChanges="orientation|keyboardHidden"
        android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
        android:windowSoftInputMode="stateAlwaysHidden"
        android:exported="false">
		</activity>
    </gap:config-file>
```

My guess is I have to change the android:name and that some of the configuration isn't needed, but I don't know what the android:name should be. Any help would be appreciated. Other ways to achieve forcing landscape on the camera are welcome as well.

**Comment by EddyVerbruggen** [comment]
Hi, you can now pass `orientation: "landscape"` to force landscape. Or `"portrait"`. Or even nothing at all so the scanner will rotate with the device. Please check out version 2.1.0.
