### ISSUE TITLE
Merge with phonegap-plugin-barcodescanner

### ISSUE THREAD

**Issue by viskin** [Telerik-Verified-Plugins/BarcodeScanner#19]
This repository pretty distantiated from [phonegap-plugin-barcodescanner](https://github.com/phonegap/phonegap-plugin-barcodescanner) (76 commits behind).
I personally have an issue with iOS on iPhone4s, that was [reported as fixed](https://github.com/wildabeast/BarcodeScanner/issues/162) there. It is serious issue that prevents our app from working correctly. And it was not fixed at Telerik-Verified.
Why not to merge the official cordova plugin to Telerik-Verified fork more often?
At least the [specified fix](https://github.com/wildabeast/BarcodeScanner/commit/a1f216d4413596ca18251c3fe543f862acf972a5).

**Comment by EddyVerbruggen** [comment]
I'll at least merge the specific fix but as you've probably also seen this repo is 40 commits ahead of the upstream. This one of the few repo's that's not quite in sync because I had to fix several issues in the past which were not fixed in the upstream and maintenance of it was slow.

**Comment by viskin** [comment]
Ok, thanks.

**Comment by EddyVerbruggen** [comment]
1.3.1 is now available and fixes the specific issue, thanks for letting me know!
