### ISSUE TITLE
Image upside down on tablet

### ISSUE THREAD

**Issue by NgYueHong** [Telerik-Verified-Plugins/BarcodeScanner#20]
I am using this plugin to add qr-code scanning function to my hybrid app. The plugin works well, except on tablet where the image is displayed upside down. This only happen on tablet, and no issue on phone. I have tried with several device, but it all happen upside down on tablet device.

How can I fix it?

**Comment by EddyVerbruggen** [comment]
Hi, could you update to 2.1.0 and test again? I had no issues on my devices but I've read that the latest release of ZXing (which we're now using) is supposed to fix this issue.

**Comment by 17cupsofcoffee** [comment]
I had the same issue on my Nexus 5X, and the 2.1.0 update seems to have fixed it.
