### ISSUE TITLE
nothing happend whit BarCodeScanner 

### ISSUE THREAD

**Issue by TaktakTaktouk** [Telerik-Verified-Plugins/BarcodeScanner#21]
I followed your tutorial on this link (http://plugins.telerik.com/cordova/plugin/barcodescanner) to add the plugin to my Barcodescanner cordova project for android.
The command : `cordova plugin add https://github.com/Telerik-Verified-Plugins/BarcodeScanner`
was well executed. also compile and launch, but when I call the scan method nothing is happening.
```
cordova.plugins.barcodeScanner.scan (

    // Success callback function
    function (result) {
        // Wrapping in a timeout so the dialog Does not the free app
        setTimeout (function () {
            alert ("We got a barcode \ n" +
                  "Result:" + result.text + "\ n" +
                  "Format" result.format + + "\ n" +
                  "Cancelled" result.cancelled +);
        }, 0);
    },

    // Error callback function
    function (error) {
        alert ("Scanning failed:" + error);
    },

    // Object options
    {
        "preferFrontCamera": false,
        "showFlipCameraButton": true
    }
```

**Comment by EddyVerbruggen** [comment]
Can you share your project? It really depends on what else is in there.

**Comment by TaktakTaktouk** [comment]
I resolved my problem and evrything working after installing phonegap with npm and node.js
