### ISSUE TITLE
Unable to see preferFrontCamera or showFlipCameraButton 

### ISSUE THREAD

**Issue by danjwilkinson** [Telerik-Verified-Plugins/BarcodeScanner#22]
Hi there,

I have set preferFrontCamera and showFlipCameraButton both to true, however it defaults to the back camera and I'm not getting an option to flip the camera. I am using the standard example:

   cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      }, 
      function (error) {
          alert("Scanning failed: " + error);
      },
      {
          "preferFrontCamera" : true,
          "showFlipCameraButton" : true,
          "prompt" : "Place a barcode inside the scan area", // supported on Android only
          "formats" : "QR_CODE,PDF_417" // default: all but PDF_417 and RSS_EXPANDED
      }
   );

Tested on iPhone 6S iOS 9.2.1 & Android Moto G 5.1. Anyone else had any issues with this or found a resolution? I've Googled this problem, however there seems to be very little support about it.

**Comment by danjwilkinson** [comment]
Sorry please close this, the issue was because I was previewing the app within Ionic View and not a proper build of the apk/ipa. It seems to strip out the extra functionality. Not sure why though.

Thanks, Dan

**Comment by EddyVerbruggen** [comment]
Ah, OK, I couldn't reproduce it :)

The reason is simple: the plugin that's bundled with Ionic View is different from the one here; it lacks these features. Here's the list they support: http://docs.ionic.io/v1.0/docs/view-usage

**Comment by danjwilkinson** [comment]
Thank you for sending that link over, it makes a lot of sense! I've got it building on both platforms now and works perfectly. You've been a massive help with one of my projects. Thank you!

**Comment by EddyVerbruggen** [comment]
:+1: Thanks!
