### ISSUE TITLE
unable to scan pdf417

### ISSUE THREAD

**Issue by sundeepa2513** [Telerik-Verified-Plugins/BarcodeScanner#23]
If I include the below in the function for scanning PDF_417 barcode, it does not do anything. I am building an app using cordova for Android

"formats": "QR_CODE,PDF_417"

**Comment by EddyVerbruggen** [comment]
Can you try again with version 2.1.0 and perhaps force orientation to landscape as I've read that works better for PSD_417. Please reopen if issues remain.
