### ISSUE TITLE
iOS app scans randomly UPC and other EAN formats when scanning EAN-13

### ISSUE THREAD

**Issue by stephen-mcculloch** [Telerik-Verified-Plugins/BarcodeScanner#25]
I thought the solution may be to limit the possible codes to scan to only EAN-13 but this can only be done in Android. Any chance this could also be added to the iOS plugin? (the attached image contains barcode type EAN_13 with code 8712811036520 but regularly scans as type UPC_E or EAN_8 with varying codes and even scans EAN_13 with the incorrect code)
![8712811036520](https://cloud.githubusercontent.com/assets/18265710/14274252/868212d8-fb10-11e5-99e1-2499600ce805.jpg)

**Comment by EddyVerbruggen** [comment]
Hi, I've just added the ability to pass in the `formats` param to iOS as well. So just install version 2.0.1 and pass in `formats: "EAN_13"` and you're good.
