### ISSUE TITLE
Can this plugin be made available on NPM?

### ISSUE THREAD

**Issue by alexbuijs** [Telerik-Verified-Plugins/BarcodeScanner#29]
Hi, thanks for the much needed update of the original version of this plugin! Is it possible to publish this plugin on NPM?

**Comment by EddyVerbruggen** [comment]
Just curious: why do you need that?

**Comment by alexbuijs** [comment]
It makes it a lot easier to detect new versions of the plugin. When just a github url is specified, on every build cordova will just pull in the changes. When discrete versions are published, I can easily review the changeset and determine whether I need to make changes to my code when updating a plugin. I think it is also the [cordova recommended way](https://cordova.apache.org/docs/en//latest/guide/hybrid/plugins/index.html#publishing-plugins) of publishing plugins.

**Comment by EddyVerbruggen** [comment]
I understand, but of course I'm asking because it's not as trivial for us as it seems.

Can you perhaps [pin against a specific release](https://github.com/Telerik-Verified-Plugins/BarcodeScanner/releases)?

**Comment by alexbuijs** [comment]
Ok, I understand. Pinning is also possible I guess, although I like being able to see which plugins are outdated through one command, without needing to visit several repos.

**Comment by EddyVerbruggen** [comment]
Yeah that is a nice feature indeed - I'll keep this open and get back on this subject.

**Comment by alexbuijs** [comment]
Awesome, thanks!

**Comment by EddyVerbruggen** [comment]
Hey @alexbuijs we've now merged our code with the PhoneGap version so we have their latest changes and they have ours. They just published the 5.0.0 version to npm which is exactly the same as the code in here, so please go ahead and grab this npm package: `phonegap-plugin-barcodescanner`.

**Comment by alexbuijs** [comment]
Thanks for all your effort, that is great news!
