### ISSUE TITLE
iOS app scanning incorrect EAN-13 barcode

### ISSUE THREAD

**Issue by stephen-mcculloch** [Telerik-Verified-Plugins/BarcodeScanner#30]
After applying the restriction to scan only EAN-13 barcodes we do in fact scan only EAN-13 barcodes but often it appears to scan the incorrect barcode.

If the barcode is initially not entirely visible and the barcode gradually comes fully into the picture then it appears to capture an incorrect value (start holding your phone very close to the barcode and move away until a barcode is scanned).

If the barcode is initially fully visible then it almost always scans the correct barcode.

Any help/suggestions/fixes would be greatly appreciated!

**Comment by stephen-mcculloch** [comment]
Has there been any progress on this issue?

**Comment by RolandVonk** [comment]
Possible solutions might be: start scanning only when the barcode has a certain width (percentage of scanning window), say 80%; or scan a barcode multiple times, and only give back results when multiple scans return the same barcode. As far as I know we cannot do something like this ourselves with this plugin.

**Comment by EddyVerbruggen** [comment]
Do you have an example of a problematic barcode to help investigate this problem?

**Comment by RolandVonk** [comment]
Hi Eddy, Thanks for replying! We have tested extensively with EAN-13 barcodes and iPhone6 phones (several). We can reproduce the issue regardless the quality (size, print quality) of the barcode by starting the scan from a distance, and then real slowly approaching the barcode. The scanner will recognize the EAN code too early, and give a false result. This will be another result everytime we try this. If we approach the barcode in another way, so take care that it fills the scanning area before the scanneer scans, we will have a 100% good result. However, that is not the way barcodes are scanned in real life unfortunately. 

Attached please find an image of a label with an EAN code we scanned, two false results we got, and the correct one.

![img_7568](https://cloud.githubusercontent.com/assets/19589962/15580427/007bd0bc-2369-11e6-9d4e-3b3516d04738.PNG)
![img_7569](https://cloud.githubusercontent.com/assets/19589962/15580424/007af0b6-2369-11e6-8ab1-2de43479be3b.PNG)
![img_7570](https://cloud.githubusercontent.com/assets/19589962/15580426/007b3490-2369-11e6-8916-dff08d96932f.JPG)
![img_7567](https://cloud.githubusercontent.com/assets/19589962/15580425/007afc8c-2369-11e6-9c6d-33394f20b38f.PNG)

**Comment by stephen-mcculloch** [comment]
Additionally, regarding the above example, the settings for the scanner in this app limit to scanning only EAN_13 while in the above example only 12 numbers are scanned. Here is the javascript opening the scanner:

cordova.plugins.barcodeScanner.scan(
	function(result) {
		setTimeout(function() {
			onScanned(result.text);
		}, 0);
	},
	{
		"preferFrontCamera": false,
		"showFlipCameraButton": false,
		"formats": 'EAN_13'
	}
);

**Comment by RolandVonk** [comment]
Hi Eddy, have you made any progress with regard to the issues we have raised?

**Comment by EddyVerbruggen** [comment]
@RolandVonk I couldn't reproduce the problem by scanning the image above (the barcode in the 3rd screenshot). It always scans correctly for me, even when starting up close or far away. Are you able to alter the native sources?

@stephen-mcculloch I hope that code sample is incorrect as the options object should be third (the error handler is missing in between).

**Comment by stephen-mcculloch** [comment]
Hello Eddy, yes I removed the error handler for simplicity in the post. It is in fact as follows:

```
cordova.plugins.barcodeScanner.scan(
	function(result) {
		if (!result.cancelled) {
			setTimeout(function() {
				onScanned(result.text);
			}, 0);
		}
	},
	function(error) {

	},
	{
		"preferFrontCamera": preferFrontCamera, // default false
		"showFlipCameraButton": showFlipCameraButton, // default false
		"formats": 'EAN_13'
	}
);
```

**Comment by EddyVerbruggen** [comment]
And are you able to change the native code in your project?

**Comment by stephen-mcculloch** [comment]
I am not sure I understand what you mean with "native code". I have simply implemented the Telerik plugin as is documented on the Telerik site:

http://plugins.telerik.com/cordova/plugin/barcodescanner

**Comment by EddyVerbruggen** [comment]
Are you building locally with the Cordova CLI (so you have direct access to the native code in the platforms/ios folder) or do you use a cloud service like Telerik Platform or PhoneGap Build?

**Comment by stephen-mcculloch** [comment]
I am using the Telerik AppBuilder platform

**Comment by EddyVerbruggen** [comment]
OK, then that's not possible. Which device do you see the problem on and please provide me with a reproducable sample.

**Comment by stephen-mcculloch** [comment]
Eddy, while creating an example project I also installed an update of the Telerik AppBuilder plugin in VIsual Studio. As a result I could not reproduce the problem in my example project. In the projects where it was a problem I re-installed the BarcodeScanner plugin and now the scanner is also working perfectly in the apps! I'm not sure how this could have occurred (since this is something I previously checked numerous times) but it seems like I was working with an old version of the barcode scanner this whole time.

Using the scanner now in the above mentioned app displays now a sharp image (camera focuses properly now) and scans a correct barcode very quickly no matter what distance or angle to attempt to scan the code.

Thanks for your help with the issue.

**Comment by EddyVerbruggen** [comment]
That's great to hear! It puzzled me why we had different results so glad that's sorted out. Cheers!
