### ISSUE TITLE
Doesn't work in Phonegap Build

### ISSUE THREAD

**Issue by kodatech** [Telerik-Verified-Plugins/BarcodeScanner#33]
Hi, the plugin doesn't work in phonegap build

**Comment by EddyVerbruggen** [comment]
Have you tried building with gradle on pgb? And please dont crosspost.

**Comment by kodatech** [comment]
No, never. Thanks for your answer and I'll take care of dont crosspost again. I'll try gradle on pgb.

**Comment by jensbits** [comment]
@kodatech I can't seem to get gradle to work on PGB. Did you ever get the barcode scanner to work with PDB?
