### ISSUE TITLE
Ability to limit scanning to center of screen

### ISSUE THREAD

**Issue by andymac4182** [Telerik-Verified-Plugins/BarcodeScanner#7]
When we have multiple barcodes to be scanned off the one sheet of paper it will sometimes pick the barcode that is not in the center of the screen. It would be great if we could specify a parameter to scan either the whole camera view or just the centered area.

**Comment by EddyVerbruggen** [comment]
I won't be able to fix that I'm afraid but in case those barcodes are of different types you can limit scanning to the relevant formats only.
